version: '3.8'
services:
  mongodb:
    image: mongo:4
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_INITDB_DATABASE: todo-list
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db1

  mongodb_replica:
    build: ./mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: prisma
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'
    volumes:
      - dbdata6:/data/db2
volumes:
  dbdata6: